iSociety.UI.Web/Areas/Admin/Controllers/CadastroController.cs
using iSociety.Models;
using System.Web.Mvc;
using iSociety.Repositorio;
using CryptSharp;

namespace iSociety.UI.Web.Areas.Admin.Controllers
{
    public class CadastroController : Controller
    {
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(UsuarioConsumidor user)
        {
            if (ModelState.IsValid)
            {                
                string senhaHash = Crypter.Blowfish.Crypt(user.Senha);
                var usuario = new QueryUsuarioConsumidor();
                if (usuario.VerificaUserName(user))
                {
                    user.Senha = senhaHash;
                    usuario.Inserir(user);
                }
                return View("UsuarioExistente");
            }
            return View(user);
        }
    }
}

iSociety.UI.Web/Areas/Usuario/Controllers/CadastroController.cs
using iSociety.Models;
using System.Web.Mvc;
using iSociety.Repositorio;
using CryptSharp;

namespace iSociety.UI.Web.Areas.Usuario.Controllers
{
    public class CadastroController : Controller
    {
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(UsuarioConsumidor user)
        {
            if (ModelState.IsValid)
            {               
                string senhaHash = Crypter.Blowfish.Crypt(user.Senha);
                var usuario = new QueryUsuarioConsumidor();
                if (usuario.VerificaUserName(user))
                {
                    user.Senha = senhaHash;
                    usuario.Inserir(user);                    
                }
                return View("UsuarioExistente");
            }
            return View(user);
        }
    }
}

iSociety.UI.Web/Controllers/CadastroController.cs
using iSociety.Models;
using System.Web.Mvc;
using iSociety.Repositorio;

namespace iSociety.UI.Web.Controllers
{
    public class CadastroController : Controller
    {
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(UsuarioConsumidor user)
        {
            if (ModelState.IsValid)
            {
                var cripto = new Cripto();
                var usuario = new QueryUsuarioConsumidor();
                var senhaHash = cripto.Hash(user.Senha);
                user.Senha = senhaHash;
                usuario.Inserir(user);
                return RedirectToAction("Index");
                //return RedirectToRoute(new{ controller = "Home", action = "About", id = UrlParameter.Optional });
            }
            return View(user);
        }
    }
}

iSociety.UI.Web/Areas/Usuario/Views/Cadastro/Index.cshtml
@model iSociety.Models.UsuarioConsumidor

@{
    ViewBag.Title = "Registro de Usuário";
}

<h2>Insira seus dados e cadastre-se no iSociety!</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">

    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.Label("Nome:", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("E-mail:", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.PasswordFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Senha:", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.PasswordFor(model => model.Senha, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Senha, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Conta Bancária:", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.contaBanco, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.contaBanco, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Registrar" class="btn btn-default" />
        </div>
    </div>
</div>
}


@section Scripts{
    @Scripts.Render("~/bundles/jqueryval")
}

iSociety.UI.Web/Areas/Usuario/Views/Cadastro/UsuarioExistente.cshtml
<h2 style="text-align:center"> O nome de usuário escolhido já existe :( </h2>
<div><h3 style="text-align:center">@Html.ActionLink("Tentar novamente", "Index", "Cadastro")</h3></div>